title: Wildlander Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
icon:  "/assets/wildlander-icon-light.png"
back_to_top: true
back_to_top_text: "Back to top"
color_scheme: dark

url: https://wildlander-mod.github.io/

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

nav_external_links:
  - title: Launcher Changelog
    Url: https://github.com/Wildlander-mod/Launcher/blob/main/CHANGELOG.md
    hide_icon: true # set to true to hide the external link icon - defaults to false
  - title: Mod Suggestions
    Url: https://trello.com/b/jQFlf7nY/suggested-mods
    hide_icon: true # set to true to hide the external link icon - defaults to false
  - title: Requiem WIKI
    url: https://www.reddit.com/r/skyrimrequiem/wiki/index
    hide_icon: true # set to true to hide the external link icon - defaults to false
  - title: UESP Interactive Skyrim Map
    url: https://srmap.uesp.net/
    hide_icon: true # set to true to hide the external link icon - defaults to false   
  - title: UESP Interactive Solstheim Map
    url: https://dbmap.uesp.net/
    hide_icon: true # set to true to hide the external link icon - defaults to false   
  - title: UESP Skill Book locations
    url: https://en.uesp.net/wiki/Skyrim:Skill_Books
    hide_icon: true # set to true to hide the external link icon - defaults to false  
   
    
