title: Wildlander Wiki
description: Starter page for wiki Dev work
theme: just-the-docs
logo: "images/wildlander-icon-dark.png"


url: wildlander-mod.github.io


search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  
