title: Wildlander Wiki
description: Starter page for wiki Dev work
theme: just-the-docs

url: wildlander-mod.github.io

aux_links: # remove if you don't want this link to appear on your pages
  To-do-list: todo.md
