title: Wildlander Wiki
description: Starter page for wiki Dev work
theme: just-the-docs
logo: "images/wildlander-icon-dark.png"


url: wildlander-mod.github.io


search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  
  
footer_content: "Copyright &copy; 2021-2022 Wildlander Team. 


last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" 

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Wildlander-mod/wildlander-mod.github.io" 
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
