title: Wildlander Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
back_to_top: true
back_to_top_text: "Back to top"
color_scheme: wider

url: https://wildlander-mod.github.io/

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

nav_external_links:
  - title: Requiem WIKI [Reddit]
    url: https://www.reddit.com/r/skyrimrequiem/wiki/index
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: UESP Interactive Skyrim Map
    url: https://srmap.uesp.net/
    hide_icon: false # set to true to hide the external link icon - defaults to false   
  - title: UESP Interactive Solstheim Map
    url: https://dbmap.uesp.net/
    hide_icon: false # set to true to hide the external link icon - defaults to false   
  - title: UESP Skill Book locations
    url: https://en.uesp.net/wiki/Skyrim:Skill_Books
    hide_icon: false # set to true to hide the external link icon - defaults to false  
  - title: UESP Wiki 
    url: https://en.uesp.net/wiki/Main_Page
    hide_icon: false # set to true to hide the external link icon - defaults to false      

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021-2022 Resonant Games."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Wildlander-mod/wildlander-mod.github.io/" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
   
callouts_level: loud
callouts:
  highlight:
    title: Notice
    color: yellow
  important:
    title: Important
    color: yellow
  new:
    title: Log Section
    color: green
  console:
    title: Console Commands
    color: green    
  note:
    color: pink
  warning:
    title: Warning
    color: red
  save:
    color: pink
    opacity: 0.3
