title: Wildlander Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://wildlander-mod.github.io/

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

nav_external_links:
  - title: Requiem WIKI
    url: https://www.reddit.com/r/skyrimrequiem/wiki/index
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: UESP Interactive Skyrim Map
    url: https://srmap.uesp.net/
    hide_icon: false # set to true to hide the external link icon - defaults to false   
  - title: UESP Interactive Solstheim Map
    url: https://dbmap.uesp.net/
    hide_icon: false # set to true to hide the external link icon - defaults to false   
  - title: UESP Skill Book locations
    url: https://en.uesp.net/wiki/Skyrim:Skill_Books
    hide_icon: false # set to true to hide the external link icon - defaults to false  
   
    
